name: CI with GitHub Actions using Ant and JUnit | © 2025 by quoc.ca

# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v3

      - name: Set up JDK 24
        uses: actions/setup-java@v3
        with:
          java-version: '24'  # Sử dụng JDK 24, kiểm tra hỗ trợ trên tài liệu actions/setup-java
          distribution: 'temurin'

      - name: Build project with Ant
        run: ant -noinput -buildfile build.xml

      - name: Distribute jar-war file
        run: mkdir staging && cp dist/*.jar staging || echo "No jar file found"

      - name: Make hyperlink to jar-war file
        uses: actions/upload-artifact@v3
        with:
          name: 1.0-SNAPSHOT.jar
          path: staging
